---
# Copyright Utrecht University

- name: Find out if group-manager privilige groups are created
  become_user: "{{ irods_service_account }}"
  become: yes
  command: 'iadmin lg'
  register: priv_groups
  changed_when: priv_groups.stdout.find('priv-group-add') == -1
  check_mode: no


- name: Configure group-manager privilige groups in iCAT database
  become_user: "{{ irods_service_account }}"
  become: yes
  command: '/etc/irods/irods-ruleset-uu/tools/group-manager-setup.sh'
  when: priv_groups.stdout.find('priv-group-add') == -1


- name: Find out which system collections are present
  become_user: "{{ irods_service_account }}"
  become: yes
  command: 'ils /{{ irods_zone }}/yoda'
  ignore_errors: True
  register: system_collections
  changed_when: False
  check_mode: no


- name: Ensure yoda system collections are present
  become_user: "{{ irods_service_account }}"
  become: yes
  command: "irule -F /etc/irods/irods-ruleset-uu/tools/create-system-collections.r '*enableRevisions={{ enable_revisions }}'"
  register: create_system_collections
  when: >
    (system_collections.stderr.find('does not exist') >= 0)
    or
    (system_collections.stdout.find('revisions') == -1
    and enable_revisions == 1)
  changed_when: create_system_collections.stdout.find('Creating') >= 0


- name: Check for existence of storage statistics script
  become_user: "{{ irods_service_account }}"
  become: yes
  stat:
    path: /etc/irods/irods-ruleset-uu/tools/monthly-storage-statistics.r
  register: monthly_storage_statistics


- name: Enable storage statistics gathering cronjob
  become_user: "{{ irods_service_account }}"
  become: yes
  cron:
    name: 'monthly-storage-statistics'
    minute: 0
    hour: 6
    day: 15
    job: '/bin/irule -F /etc/irods/irods-ruleset-uu/tools/monthly-storage-statistics.r >> $HOME/log/job_monthly-storage-statistics.log 2>&1'
  when: monthly_storage_statistics.stat.exists == True


- name: Set configuration AVUs to system collection
  become_user: "{{ irods_service_account }}"
  become: yes
  irods_setavu:
    name: "/{{ irods_zone }}/yoda"
    irods_type: Collection
    attribute: "{{ avu.attribute }}"
    value: "{{ avu.value }}"
  with_items:
    - attribute: org_comanage_rest_api
      value: "{{ comanage_rest_api }}"
  loop_control:
    loop_var: avu
