---
# copyright Utrecht University

- name: Ensure davrods prerequisites are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - boost
  - jansson

- name: Check if davrods is installable from repository
  yum:
    list: '{{ davrods.package }}'
  register: davrods_repo
  

- name: Download davrods rpm
  get_url:
    url: '{{ davrods.url }}/{{ davrods.filename }}'
    dest: '{{ rpm_dest_dir }}/{{ davrods.filename }}'
    checksum: '{{ davrods.checksum }}'
  when: not davrods_repo.results


- name: Install davrods from downloaded rpm
  package:
    name: '{{ rpm_dest_dir }}/{{ davrods.filename }}'
    state: present
  when: not davrods_repo.results and not ansible_check_mode


- name: Ensure davrods rpm is installed
  package:
    name: '{{ davrods.package }}'
    state: present
  when: davrods_repo.results and not ansible_check_mode


- name: Allow Apache to execute davrods module
  sefcontext:
    target: /etc/httpd/modules/mod_davrods.so
    setype: httpd_sys_script_exec_t
    state: present
  register: filecontext


- name: Ensure selinux context is enforced on davrods module
  shell: restorecon /etc/httpd/modules/{{ item.target }}
  when: filecontext is changed and ansible_selinux
  with_items:
  - { index: 0, target: 'mod_davrods.so' }


- name: Copy irods_enviroment.json to /etc/httpd/irods/irods_environment.json
  template:
    src: irods_environment.j2
    dest: /etc/httpd/irods/irods_environment.json
    owner: apache
    group: apache
    mode: 0644
  notify: Restart Apache webserver


- name: Copy davrods Apache configuration
  template:
    src: davrods-vhost.conf.j2
    dest: /etc/httpd/conf.d/davrods-vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Apache webserver


- name: Copy davrods anonymous Apache configuration
  template:
    src: davrods-anonymous-vhost.conf.j2
    dest: /etc/httpd/conf.d/davrods-anonymous-vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Apache webserver


- name: Allow Apache to execute iRODS network plugins
  sefcontext:
    target: '{{ item }}'
    setype: httpd_sys_script_exec_t
    state: present
  register: filecontext
  with_items:
    - /usr/lib/irods/plugins/network/libtcp_client.so
    - /usr/lib/irods/plugins/network/libssl_client.so
    - /usr/lib/irods/plugins/network/libtcp_server.so
    - /usr/lib/irods/plugins/network/libssl_server.so


- name: Ensure selinux context is enforced on iRODS network plugins
  shell: restorecon /usr/lib/irods/plugins/network/{{ item.target }}
  when: filecontext.results[item.index] is changed and ansible_selinux
  with_items:
  - { index: 0, target: 'libtcp_client.so' }
  - { index: 1, target: 'libssl_client.so' }
  - { index: 2, target: 'libtcp_server.so' }
  - { index: 3, target: 'libssl_server.so' }


- name: Allow public to ports for davrods in firewall
  firewalld:
    port: '{{ yoda_davrods_port }}/tcp'
    permanent: true
    state: enabled
    immediate: yes
  notify: Restart firewall


- name: Allow public to ports for anonymous davrods in firewall
  firewalld:
    port: '{{ yoda_davrods_anonymous_port }}/tcp'
    permanent: true
    state: enabled
    immediate: yes
  notify: Restart firewall


- name: Ensure styling of davrods directory listing is present
  template:
    src: '{{ item.src }}'
    dest: '/etc/httpd/irods/{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  with_items:
  - { src: head.html.j2, dest: 'head.html' }
  - { src: header.html.j2, dest: 'header.html' }
  - { src: footer.html.j2, dest: 'footer.html' }

