---
# copyright Utrecht University

- name: Prepare test data for removal
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    ichmod -rM own rods '{{ item }}'
  ignore_errors: true
  with_items:
    - /tempZone/home/vault-deletegroup
    - /tempZone/home/vault-i1
    - /tempZone/home/vault-initial
    - /tempZone/home/vault-initial1
    - /tempZone/home/vault-mdtest
    - /tempZone/home/vault-process1
    - /tempZone/home/vault-process2
    - /tempZone/home/vault-process3
    - /tempZone/home/vault-r1
    - /tempZone/home/vault-revisions
    - /tempZone/home/vault-search
    - /tempZone/home/vault-updateproperties
    - /tempZone/home/grp-datamanager-initial
    - /tempZone/home/grp-datamanager-test
    - /tempZone/home/grp-g1
    - /tempZone/home/grp-intake-initial
    - /tempZone/home/grp-intake-test
    - /tempZone/home/grp-vault-initial
    - /tempZone/home/grp-vault-test
    - /tempZone/home/intake-i1
    - /tempZone/home/datamanager-frontendtest
    - /tempZone/home/datamanager-initial
    - /tempZone/home/research-deletegroup
    - /tempZone/home/research-initial
    - /tempZone/home/research-initial1
    - /tempZone/home/research-mdtest
    - /tempZone/home/research-process1
    - /tempZone/home/research-process2
    - /tempZone/home/research-process3
    - /tempZone/home/research-r1
    - /tempZone/home/research-revisions
    - /tempZone/home/research-search
    - /tempZone/home/research-updateproperties
    - /tempZone/trash/home/research-deletegroup
    - /tempZone/trash/home/research-initial
    - /tempZone/trash/home/research-initial1
    - /tempZone/trash/home/research-mdtest
    - /tempZone/trash/home/research-process1
    - /tempZone/trash/home/research-process2
    - /tempZone/trash/home/research-process3
    - /tempZone/trash/home/research-r1
    - /tempZone/trash/home/research-revisions
    - /tempZone/trash/home/research-search
    - /tempZone/trash/home/research-updateproperties
    - /tempZone/yoda/revisions/research-deletegroup
    - /tempZone/yoda/revisions/research-initial
    - /tempZone/yoda/revisions/research-initial1
    - /tempZone/yoda/revisions/research-mdtest
    - /tempZone/yoda/revisions/research-process1
    - /tempZone/yoda/revisions/research-process2
    - /tempZone/yoda/revisions/research-process3
    - /tempZone/yoda/revisions/research-r1
    - /tempZone/yoda/revisions/research-revisions
    - /tempZone/yoda/revisions/research-search
    - /tempZone/yoda/revisions/research-updateproperties


- name: Remove test data
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    irm -r '{{ item }}'
  ignore_errors: true
  with_items:
    - /tempZone/home/vault-deletegroup
    - /tempZone/home/vault-i1
    - /tempZone/home/vault-initial
    - /tempZone/home/vault-initial1
    - /tempZone/home/vault-mdtest
    - /tempZone/home/vault-process1
    - /tempZone/home/vault-process2
    - /tempZone/home/vault-process3
    - /tempZone/home/vault-r1
    - /tempZone/home/vault-revisions
    - /tempZone/home/vault-search
    - /tempZone/home/vault-updateproperties
    - /tempZone/home/grp-datamanager-initial
    - /tempZone/home/grp-datamanager-test
    - /tempZone/home/grp-g1
    - /tempZone/home/grp-intake-initial
    - /tempZone/home/grp-intake-test
    - /tempZone/home/grp-vault-initial
    - /tempZone/home/grp-vault-test
    - /tempZone/home/intake-i1
    - /tempZone/home/datamanager-frontendtest
    - /tempZone/home/datamanager-initial
    - /tempZone/home/research-deletegroup
    - /tempZone/home/research-initial
    - /tempZone/home/research-initial1
    - /tempZone/home/research-mdtest
    - /tempZone/home/research-process1
    - /tempZone/home/research-process2
    - /tempZone/home/research-process3
    - /tempZone/home/research-r1
    - /tempZone/home/research-revisions
    - /tempZone/home/research-search
    - /tempZone/home/research-updateproperties
    - /tempZone/trash/home/research-deletegroup
    - /tempZone/trash/home/research-initial
    - /tempZone/trash/home/research-initial1
    - /tempZone/trash/home/research-mdtest
    - /tempZone/trash/home/research-process1
    - /tempZone/trash/home/research-process2
    - /tempZone/trash/home/research-process3
    - /tempZone/trash/home/research-r1
    - /tempZone/trash/home/research-revisions
    - /tempZone/trash/home/research-search
    - /tempZone/trash/home/research-updateproperties
    - /tempZone/yoda/revisions/research-deletegroup
    - /tempZone/yoda/revisions/research-initial
    - /tempZone/yoda/revisions/research-initial1
    - /tempZone/yoda/revisions/research-mdtest
    - /tempZone/yoda/revisions/research-process1
    - /tempZone/yoda/revisions/research-process2
    - /tempZone/yoda/revisions/research-process3
    - /tempZone/yoda/revisions/research-r1
    - /tempZone/yoda/revisions/research-revisions
    - /tempZone/yoda/revisions/research-search
    - /tempZone/yoda/revisions/research-updateproperties


- name: Remove test groups
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    iadmin rmgroup '{{ item }}'
  ignore_errors: true
  with_items:
    - vault-deletegroup
    - vault-i1
    - vault-initial
    - vault-initial1
    - vault-mdtest
    - vault-process1
    - vault-process2
    - vault-process3
    - vault-r1
    - vault-revisions
    - vault-search
    - vault-updateproperties
    - research-deletegroup
    - research-initial
    - research-initial1
    - research-mdtest
    - research-process1
    - research-process2
    - research-process3
    - research-r1
    - research-revisions
    - research-search
    - research-updateproperties
    - read-deletegroup
    - read-initial
    - read-initial1
    - read-mdtest
    - read-process1
    - read-process2
    - read-process3
    - read-r1
    - read-revisions
    - read-search
    - read-updateproperties
    - datamanager-frontendtest
    - datamanager-initial
    - grp-datamanager-initial
    - grp-datamanager-test
    - grp-intake-initial
    - grp-intake-test
    - grp-vault-initial
    - grp-vault-test
    - grp-g1
    - intake-i1
    - read-i1
    - read-test


- name: Remove test users
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    iadmin rmuser '{{ item }}'
  ignore_errors: true
  with_items:
    - createnewuser


- name: Ensure test users exists
  user:
    name: '{{ item.name }}'
    password: "{{ item.password | password_hash('sha512') }}"
  with_items: '{{ test_users }}'


- name: Ensure Yoda test users exists
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_mkuser:
    name: '{{ item.name }}'
  with_items: '{{ test_users }}'


- name: Ensure Yoda test users have type
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_moduser:
    name: '{{ item.name }}'
    option: 'type'
    value: '{{ item.type }}'
  with_items: '{{ test_users }}'


- name: Ensure Yoda test users have password
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_moduser:
    name: '{{ item.name }}'
    option: 'password'
    value: '{{ item.password }}'
  with_items: '{{ test_users }}'


- name: Ensure Yoda test groups exists
  become_user: '{{ irods_service_account }}'
  become: yes
  yoda_addgroup:
    groupName: '{{ item.groupName }}'
    category: '{{ item.category }}'
    subcategory: '{{ item.subcategory }}'
    description: 'Auto-generated by Ansible'
  with_items: '{{ test_groups }}'


- name: Ensure Yoda users are added to groups
  become_user: '{{ irods_service_account }}'
  become: yes
  yoda_addgroupuser:
    groupName: '{{ item.groupName }}'
    user: '{{ item.user }}'
    role: '{{ item.role }}'
  with_items: '{{ test_groupusers }}'


- name: Ensure Yoda intake datamanager has read access to grp-vault folders
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    ichmod -M read grp-datamanager-initial /tempZone/home/grp-vault-initial
  ignore_errors: true


- name: Ensure Yoda intake datamanager has read access to grp-vault folders
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    ichmod -M read grp-datamanager-test /tempZone/home/grp-vault-test
  ignore_errors: true


- name: Ensure Yoda test data directory is present in Yoda
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    imkdir /{{ irods_zone }}/home/research-initial/testdata
  ignore_errors: true


- name: Ensure Yoda test data directory is present
  become_user: '{{ irods_service_account }}'
  become: yes
  file:
    path: '~/testdata/'
    state: directory
    mode: 0755


- name: Ensure Yoda test data directory is present in Yoda
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    imkdir /{{ irods_zone }}/home/research-initial/testdata
  ignore_errors: true

- name: Ensure Yoda test data directory is present in Yoda
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    imkdir /{{ irods_zone }}/home/research-mdtest/nomdpresent
  ignore_errors: true

- name: Ensure Yoda test data directory is present in Yoda
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    imkdir /{{ irods_zone }}/home/research-mdtest/copyfromparent
  ignore_errors: true

- name: Ensure Yoda test files are present
  become_user: '{{ irods_service_account }}'
  become: yes
  copy:
    src: '{{ item }}'
    dest: '~/testdata/{{ item }}'
    mode: 0644
  with_items:
    - 'lorem.txt'
    - 'SIPI_Jelly_Beans_4.1.07.tiff'


- name: Ensure Yoda test files are present in Yoda
  become_user: '{{ irods_service_account }}'
  become: yes
  shell:
    iput -f ~/testdata/{{ item }} /{{ irods_zone }}/home/research-initial/testdata
  with_items:
    - 'lorem.txt'
    - 'SIPI_Jelly_Beans_4.1.07.tiff'


- name: Ensure intake module cronjob rules are present
  become_user: '{{ irods_service_account }}'
  become: yes
  copy:
    src: '{{ item }}'
    dest: '~/.irods/{{ item }}'
    mode: 0644
  with_items:
    - 'job_movetovault.r'
    - 'job_checksums.r'


- name: Configure cronjob to move grp-intake-* datapackages to the grp-vault-*
  become_user: '{{ irods_service_account }}'
  become: yes
  cron:
    name: 'job_movetovault.r'
    minute: '*'
    job: '/bin/irule -F /var/lib/irods/.irods/job_movetovault.r >>$HOME/log/job_movetovault.log 2>&1'


- name: Configure cronjob to make checksums of datapackages in grp-vault-*
  become_user: '{{ irods_service_account }}'
  become: yes
  cron:
    name: 'job_checksums.r'
    minute: '*'
    job: '/bin/irule -F /var/lib/irods/.irods/job_checksums.r >>$HOME/log/job_checksums.log 2>&1'


- name: Ensure Yoda licenses directory is present
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    imkdir /{{ irods_zone }}/yoda/licenses
  ignore_errors: true


- name: Ensure licenses are present in Yoda
  become_user: '{{ irods_service_account }}'
  become: yes
  command:
    iput -f '/etc/irods/irods-ruleset-research/tools/licenses/{{ item }}' '/{{ irods_zone }}/yoda/licenses/{{ item }}'
  with_items:
    - "Creative Commons Attribution 4.0 International Public License.txt"
    - "Creative Commons Attribution 4.0 International Public License.uri"
    - "Creative Commons Attribution-ShareAlike 4.0 International Public License.txt"
    - "Creative Commons Attribution-ShareAlike 4.0 International Public License.uri"
    - "Open Data Commons Attribution License (ODC-By) v1.0.txt"
    - "Open Data Commons Attribution License (ODC-By) v1.0.uri"
